import { Metadata } from "next";
import { Inter } from "next/font/google";
import TheHeader from "../components/TheHeader/TheHeader";
import TheFooter from "../components/TheFooter/TheFooter";
import s from "./layout_s.module.css";
import { ReduxProvider } from "@/ReduxProvier";
import { Provider } from "react-redux";
import { store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rick-n-Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />

        <div className={s.content}>
          <main className={s.main}>
            <ReduxProvider>
            {/* <Provider store={store}> */}
              {children}
              {/* </Provider> */}
              </ReduxProvider>
          </main>
        </div>

        <TheFooter />
      </body>
    </html>
  );
}
